[project]
name = "pac-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.9",
    "mazegenerator",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "pygame>=2.6.1",
    "torch>=2.13.0",
    "troch>=0.0.2",
]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.0.2-py3-none-any.whl" }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.0",
]
